[metadata]
addr = 0x400664
size = 0x89
last_change = 2023-07-26T11:51:43.168429Z

[header]
last_change = 2023-07-26T11:51:43.164429Z
name = "authenticate"
addr = 0x400664
type = "_BOOL8"

[stack_vars.-0x18]
offset = 0x10
name = "buf"
type = "char[12]"
size = 0xc
addr = 0x400664

[stack_vars.-0xc]
offset = 0x1c
name = "fd"
type = "int"
size = 0x4
addr = 0x400664

[header.args.0]
offset = 0x0
name = "kekkekkek"
type = "const char *"
size = 0x8

[header.args.1]
offset = 0x1
name = "a2"
type = "const char *"
size = 0x8
