[metadata]
addr = 0x400664
size = 0x89
last_change = 2023-07-26T11:51:17.578295Z

[header]
last_change = 2023-07-26T11:51:17.578295Z
name = "authenticate"
addr = 0x400664
type = "_BOOL8"

[header.args.0]
offset = 0x0
name = "kekkekkek"
type = "const char *"
size = 0x8

[header.args.1]
offset = 0x1
name = "a2"
type = "const char *"
size = 0x8
